project_name: smya
builds:
  - 
    id: "build"
    main: ./main.go
    binary: smya
    
    ldflags:
     - -s -w
     
    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
      
    goarm:
      - 6
      - 7

    gomips:
      - hardfloat
      - softfloat

    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: mips
      - goos: darwin
        goarch: mipsle
      - goos: darwin
        goarch: mips64
      - goos: darwin
        goarch: mips64le
      - goos: windows
        goarch: mips
      - goos: windows
        goarch: mipsle
      - goos: windows
        goarch: mips64
      - goos: windows
        goarch: mips64le 

archives:
  format_overrides:
    - goos: windows
      format: zip
  
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:' 
