builds:
  - 
    id: "build"
    main: ./main.go
    
    ldflags:
     - -s -w
     
    env:
      - CGO_ENABLED=0

    goos:
      - linux
      - windows
      - darwin

    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
      
    goarm:
      - 6
      - 7

    gomips:
      - hardfloat
      - softfloat

    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: mips
      - goos: windows
        goarch: mipsle
      - goos: windows
        goarch: mips64
      - goos: windows
        goarch: mips64le

    skip: false
    
    
